export const styles = {
  page: 'page',
  topbar: 'topbar',
  brand: 'brand',
  mark: 'mark',
  nav: 'nav',
  hero: 'hero',
  heroCopy: 'hero-copy',
  heroProof: 'hero-proof',
  eyebrow: 'eyebrow',
  lead: 'lead',
  ctaRow: 'cta-row',
  button: 'button',
  primaryButton: 'button primary',
  secondaryButton: 'button secondary',
  metricGrid: 'metric-grid',
  metric: 'metric',
  section: 'section',
  sectionHeader: 'section-header',
  featureGrid: 'feature-grid',
  card: 'card',
  demoShell: 'demo-shell',
  pipeline: 'pipeline',
  pipelineStep: 'pipeline-step',
  pipelineStepActive: 'pipeline-step active',
  demoControls: 'demo-controls',
  demoState: 'demo-state',
  panel: 'panel',
  codeBlock: 'code-block',
  comparisonGrid: 'comparison-grid',
  comparisonRow: 'comparison-row',
  footer: 'footer',
} as const
